<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="36" started-at="2018-09-23T05:33:52Z" finished-at="2018-09-23T05:33:52Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="36" started-at="2018-09-23T05:33:52Z" finished-at="2018-09-23T05:33:52Z">
      <class name="testpackage.Test_01">
        <test-method status="PASS" signature="BeforeTest()[pri:0, instance:testpackage.Test_01@4678c730]" name="BeforeTest" is-config="true" duration-ms="7" started-at="2018-09-23T05:33:52Z" finished-at="2018-09-23T05:33:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeTest -->
        <test-method status="PASS" signature="beforeclass()[pri:0, instance:testpackage.Test_01@4678c730]" name="beforeclass" is-config="true" duration-ms="0" started-at="2018-09-23T05:33:52Z" finished-at="2018-09-23T05:33:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeclass -->
        <test-method status="FAIL" signature="addtest1()[pri:0, instance:testpackage.Test_01@4678c730]" name="addtest1" duration-ms="8" started-at="2018-09-23T05:33:52Z" finished-at="2018-09-23T05:33:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at testpackage.Test_01.addtest1(Test_01.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addtest1 -->
        <test-method status="PASS" signature="beforemethod()[pri:0, instance:testpackage.Test_01@4678c730]" name="beforemethod" is-config="true" duration-ms="0" started-at="2018-09-23T05:33:52Z" finished-at="2018-09-23T05:33:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:testpackage.Test_01@4678c730]" name="aftermethod" is-config="true" duration-ms="0" started-at="2018-09-23T05:33:52Z" finished-at="2018-09-23T05:33:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="PASS" signature="beforemethod()[pri:0, instance:testpackage.Test_01@4678c730]" name="beforemethod" is-config="true" duration-ms="1" started-at="2018-09-23T05:33:52Z" finished-at="2018-09-23T05:33:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method status="PASS" signature="addtest2()[pri:0, instance:testpackage.Test_01@4678c730]" name="addtest2" duration-ms="0" started-at="2018-09-23T05:33:52Z" finished-at="2018-09-23T05:33:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addtest2 -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:testpackage.Test_01@4678c730]" name="aftermethod" is-config="true" duration-ms="1" started-at="2018-09-23T05:33:52Z" finished-at="2018-09-23T05:33:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="FAIL" signature="addtest3()[pri:0, instance:testpackage.Test_01@4678c730]" name="addtest3" duration-ms="1" started-at="2018-09-23T05:33:52Z" finished-at="2018-09-23T05:33:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at testpackage.Test_01.addtest3(Test_01.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addtest3 -->
        <test-method status="PASS" signature="beforemethod()[pri:0, instance:testpackage.Test_01@4678c730]" name="beforemethod" is-config="true" duration-ms="0" started-at="2018-09-23T05:33:52Z" finished-at="2018-09-23T05:33:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:testpackage.Test_01@4678c730]" name="aftermethod" is-config="true" duration-ms="0" started-at="2018-09-23T05:33:52Z" finished-at="2018-09-23T05:33:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="PASS" signature="afterclass()[pri:0, instance:testpackage.Test_01@4678c730]" name="afterclass" is-config="true" duration-ms="0" started-at="2018-09-23T05:33:52Z" finished-at="2018-09-23T05:33:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterclass -->
        <test-method status="PASS" signature="AfterTest()[pri:0, instance:testpackage.Test_01@4678c730]" name="AfterTest" is-config="true" duration-ms="0" started-at="2018-09-23T05:33:52Z" finished-at="2018-09-23T05:33:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterTest -->
      </class> <!-- testpackage.Test_01 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
